### ISSUE TITLE
[Co-op]Optimize Review Comment

### ISSUE THREAD

**Issue by zhenkangub** [junjieChen0608/CourseRadar#46]
Currently we fully display the comment of a reviewer.
If one user has a huge amount of comment, we may encounter a situation where we have to scroll down the review list many times in order to see the next reviewer. 

So it will be great if we could:
1: limit the the lines of comment,  and add three "..." in the end. 
2: only if we click on the comment, then a new window pop up to show the full comment.

Luckily, with android,  those two functionally can be easily completed. 
for 1: we should modify the comment TextView in reviews_list_item.xml (add two lines of code should get this work done)

for 2: setOnItemClickListener to lvReviewsList in DetailedViewActivity, then create a new Dialog. (Dialog is very handy and easy to use in Android)

This task will mainly done in "coop/opt-review-comment"

**Comment by junjieChen0608** [comment]
This issue is closed by #59
