### ISSUE TITLE
[Co-op] Optimize Code Structure

### ISSUE THREAD

**Issue by cheng09** [junjieChen0608/CourseRadar#47]
Currently we used parseUBIT and isUBEmail functions declared in DrawerActivity in some other Activities to check if users log in with their UBIT. What I need help is to optimize this code structure to build a better way to check user email address in different Activities, such as create a new class and make this to be a static method.
This task will mainly done in "coop/opt-code-structure" branch

**Comment by junjieChen0608** [comment]
Tested on Smartisan T2 and Google Pixel, all good, closed by pull req #52
